import React, { useState } from "react";
import { Bookmark, ChevronDown, ChevronUp } from "react-feather";
import { useNavigate } from "react-router-dom";
import {
  Col,
  Row,
  Accordion,
  AccordionBody,
  AccordionHeader,
  AccordionItem,
} from "reactstrap";
import "./home.css";
import SearchBar from "./SearchBar";
import "./homeBAckground.css";
export default function Home() {
  const [results, setResults] = useState();
  const navigate = useNavigate();
  const [open, setOpen] = useState("1");
  const toggle = (id) => {
    if (open === id) {
      setOpen();
    } else {
      setOpen(id);
    }
  };
  return (
    <>
      <HeaderSpace navigate={navigate} />
      <Row className="m-0 p-0">
        <Col md={2}>
          <h6 >Training Catolog</h6>
          <Accordion open={open} toggle={toggle}>
            <AccordionItem>
              <AccordionHeader targetId="1" style={{ fontSize: "3px" }}>
                NASA RESOURCES
              </AccordionHeader>
              <AccordionBody accordionId="1">
                This link should automatically download a spreadsheet containing
                all ARSET training information. If clicking on the link does not
                begin the download, please consider copying and pasting the link
                into a browser.
              </AccordionBody>
            </AccordionItem>
            <AccordionItem>
              <AccordionHeader targetId="2">
                EUROPEAN SPACE AGENCY
              </AccordionHeader>
              <AccordionBody accordionId="2">
                European Space Agency Training and Education
              </AccordionBody>
            </AccordionItem>
            <AccordionItem>
              <AccordionHeader targetId="3">
                COMISIÓN NACIONAL...
              </AccordionHeader>
              <AccordionBody accordionId="3">
                Massive Training Unit Online beginner courses on Earth
                Observation. Instituto de Altos Estudios Espaciales Mario Gulich
                Capacity-building opportunities offered at the institute.
              </AccordionBody>
            </AccordionItem>
            <AccordionItem>
              <AccordionHeader targetId="4">
                CANADIAN SPACE AGENCY
              </AccordionHeader>
              <AccordionBody accordionId="4">
                This free e-course explains how synthetic aperture radar (SAR)
                is used in Canada for research, development, and in operational
                environments for mapping and environmental monitoring. SAR data
                is very useful for environmental monitoring and responding to
                natural disasters (notably because it can image day or night, no
                matter the weather). It's a vital part of policy and
                decision-makers' toolboxes.
              </AccordionBody>
            </AccordionItem>
            <AccordionItem>
              <AccordionHeader targetId="6">
                BRAZILIAN SPACE AGENCY
              </AccordionHeader>
              <AccordionBody accordionId="6">
                INPE's images catalog provides a database with thousands of
                images generated by more than 16 satellites, with resolutions
                varying from 2 meters to 64 meters. Cameras include
                multispectral, wide field, panchromatic, among others. All
                images are available to the public in the linked platform, which
                integrates search tools for filtering the database.
              </AccordionBody>
            </AccordionItem>
            <AccordionItem>
              <AccordionHeader targetId="7">
                OTHER EXAMPLE RESOURCES
              </AccordionHeader>
              <AccordionBody accordionId="7">
                The United Nations Platform for Space-based Information for
                Disaster Management and Emergency Response (UN-SPIDER) Knowledge
                Portal
              </AccordionBody>
            </AccordionItem>
          </Accordion>
        </Col>
        <Col md={8}>
          <SearchBar results={results} setResults={setResults} />
          <Row className="p-0 mt-3 m-0">
            {/* <Col md={2} xs={0} sm={0}></Col> */}
            <Col md={12}>
              {results &&
                results.map((item, index) => (
                  <div className="d-flex">
                    {/* <div className="col-md-8 col-xs-9 col-sm-9"> */}
                    <div style={{ marginRight: "5px" }}>
                      <ChevronUp size={27} color="grey" />
                      <div style={{ marginLeft: "7px" }}>{item.vote}</div>
                      <ChevronDown size={27} color="grey" />{" "}
                    </div>
                    <div>
                      <p style={{ fontSize: "11px" }} className="m-0">
                        {item._source.link}
                      </p>
                      <h4
                        className="sub-heading m-0"
                        onClick={() => {
                          window.location.replace(item._source.link);
                        }}
                      >
                        <Bookmark size={20} color="grey" />
                        {item._source.title}
                      </h4>
                      {/* ⭐⭐⭐ */}
                      <p>
                        <span style={{ color: "rgb(92, 89, 89)" }}>
                          {index + 1} days ago —{" "}
                        </span>
                        {item._source.description}
                      </p>
                      <br />
                    </div>
                  </div>
                ))}
            </Col>
            {/* <Col md={2} xs={0} sm={0}></Col> */}
          </Row>
        </Col>
        <Col md={2} />
      </Row>

      <Row className="p-0 mt-3 m-0">
        <Col md={2} xs={0} sm={0}></Col>
        <Col md={8}>
          {results &&
            results.map((item, index) => (
              <div className="d-flex">
                {/* <div className="col-md-8 col-xs-9 col-sm-9"> */}
                <div style={{ marginRight: "5px" }}>
                  <ChevronUp size={27} color="grey" />
                  <div style={{ marginLeft: "7px" }}>{item.vote}</div>
                  <ChevronDown size={27} color="grey" />{" "}
                </div>
                <div>
                  <p style={{ fontSize: "11px" }} className="m-0">
                    {item._source.link}
                  </p>
                  <h4 className="sub-heading m-0">
                    <a
                      href={item._source.link}
                      target="_blank"
                      rel="noreferrer"
                    >
                      {item._source.title}
                    </a>
                    <Bookmark size={20} color="grey" />
                  </h4>
                  {/* ⭐⭐⭐ */}
                  <p>
                    <span style={{ color: "rgb(92, 89, 89)" }}>
                      {index + 1} days ago —{" "}
                    </span>
                    {item._source.description}
                  </p>
                  <br />
                </div>
              </div>
            ))}
        </Col>
        <Col md={2} xs={0} sm={0}></Col>
      </Row>
      <div class="view">
        <div class="plane main">
          <div class="circle"></div>
          <div class="circle"></div>
          <div class="circle"></div>
          <div class="circle"></div>
          <div class="circle"></div>
          <div class="circle"></div>
        </div>
      </div>
    </>
  );
}

export const HeaderSpace = ({ navigate }) => {
  return (
    <>
      <div id="header">
        <nav>
          <label className="logo">
            <div
              style={{ cursor: "pointer" }}
              onClick={() => {
                navigate("/");
              }}
            >
              Space Gateway
            </div>
          </label>
          <ul>
            <li>
              <span
                onClick={() => navigate("/live")}
                style={{ textDecoration: "none", cursor: "pointer" }}
              >
                Live stream
              </span>
            </li>
            <li>
              <span
                onClick={() => navigate("/publish")}
                style={{ textDecoration: "none", cursor: "pointer" }}
              >
                Publish
              </span>
            </li>
            <li>
              <span
                onClick={() => navigate("/sign-up")}
                style={{ textDecoration: "none", cursor: "pointer" }}
              >
                Sign Up
                <i className="fas fa-caret-down"></i>
              </span>
              <ul></ul>
            </li>
            <li>
              <span
                onClick={() => navigate("/login")}
                style={{ textDecoration: "none", cursor: "pointer" }}
              >
                Login
              </span>
            </li>
          </ul>
        </nav>
      </div>
    </>
  );
};
